vim.api.nvim_create_autocmd("FileType", {
  pattern = {
    "bash",
    "c",
    "checkhealth",
    "comment",
    "cpp",
    "css",
    "csv",
    "dhall",
    "diff",
    "dockerfile",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "gleam",
    "go",
    "gomod",
    "gosum",
    "gotmpl",
    "graphql",
    "haskell",
    "html",
    "javascript",
    "jsdoc",
    "json",
    "jsonc",
    "just",
    "latex",
    "lua",
    "make",
    "markdown",
    "markdown_inline",
    "nix",
    "nu",
    "php",
    "purescript",
    "python",
    "qmldir",
    "qmljs",
    "toml",
    "tsx",
    "typescript",
    "typst",
    "yaml",
    "yuck",
  },

  callback = function(ev)
    vim.api.nvim_buf_call(ev.buf, function()
      vim.treesitter.start()
    end)
  end,
})
