vim.api.nvim_create_autocmd("FileType", {
  pattern = {
    "bash",
    "c",
    "comment",
    "cpp",
    "cs",
    "razor",
    "css",
    "csv",
    "diff",
    "dockerfile",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "go",
    "html",
    "javascript",
    "jsdoc",
    "json",
    "just",
    "lua",
    "make",
    "markdown",
    "markdown_inline",
    "nix",
    "python",
    "qml",
    "qmldir",
    "qmljs",
    "sh",
    "toml",
    "tsx",
    "typescript",
    "typescriptreact",
    "yaml",
  },

  callback = function(ev)
    vim.api.nvim_buf_call(ev.buf, function()
      vim.treesitter.start()
    end)
  end,
})
