name: Build & Release

on:
  workflow_dispatch:
  # push:
  #   branches: [master]
  #   paths:
  #     - "**.nix"
  #     - "**.lock"
  #     - "**.lua"
  #     - ".github/workflows/check.yaml"

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Poke cachix
        uses: cachix/cachix-action@master
        with:
          name: anturated
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build
        run: nix build
