name: Update Flake Inputs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Update all inputs
        id: update-lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.GH_TOKEN_UPDATES }}
          git-author-name: Caterpillar
          git-author-email: pill@anturated.dev
          git-committer-name: Caterpillar
          git-committer-email: pill@anturated.dev
          commit-msg: "flake: bump (auto)"
          pr-title: "flake: bump (auto)"
          branch: pill-flake-update
          pr-body: |
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```

      - name: Merge
        if: steps.update-lock.outputs.pull-request-url != ''
        run: |
          gh pr merge --rebase --delete-branch "$PR"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_UPDATES }}
          PR: ${{ steps.update-lock.outputs.pull-request-url }}
